### PR TITLE
fix: prioritize runtime deps envars

### PR DESCRIPTION
**Pull request by staktrace**
Fixes https://github.com/cashapp/hermit/issues/368. See individual commit messages for details.

### CODE REVIEW

**Review by alecthomas — APPROVED** [review]

**Comment by alecthomas** [comment]
I can't think of a situation where this would be problematic, so this seems reasonable to me. Thanks Kats.

**Comment by alecthomas** [comment]
Oh and thanks for the very thorough test in the new test system!

**Comment by staktrace** [comment]
Thanks @alecthomas ! It looks like the change needs to be tagged in order to have a new release published, could you please do that too?

**Comment by alecthomas** [comment]
Done!

**Pull request merged**
