### PR TITLE
Refactor activate script to fix runtime errors

### PR DESCRIPTION
**Pull request by quad**
Fixes: #262

### CODE REVIEW

**Review by OmarTawfik — CHANGES_REQUESTED** [review]
Passing back to you for https://github.com/cashapp/hermit/issues/262#issuecomment-1123019831

**Comment by alecthomas** [comment]
It doesn't look like this complies with what was described in that comment? Deactivation is occurring after the function is redefined, not before?

**Comment by alecthomas** [comment]
I think what we want to do here is:

```
if deactivate-hermit is defined:
  call deactivate-hermit
elif ACTIVE_HERMIT is defined:
  call eval "$(${ACTIVE_HERMIT}/bin/hermit env --deactivate-from-ops="${HERMIT_ENV_OPS}")"  
fi
```

**Comment by OmarTawfik** [comment]
@quad are you still looking into this? happy to help/pick it up if you are not.

**Pull request closed without merging**
