### PR TITLE
Verify installer script checksum when bootstrapping

### PR DESCRIPTION
**Pull request by syncom**
We verify the downloaded install script's SHA-256 value against a known
checksum in bin/hermit. This ensures the integrity of the installer
when bootstrapping hermit.
    
We version (via file name suffix) the install script by the script's
short hash value, so that an install script can be uniquely identified
by its version / file name. The corresponding bin/hermit is generated
with hermit init for a project.
    
Note that an install script's version" is unrelated to the version of
the hermit executable.

### CODE REVIEW

**Comment by syncom** [comment]
This PR is built on top of https://github.com/cashapp/hermit/pull/273.

**Review by alecthomas — APPROVED** [review]

**Comment by syncom** [comment]
## Manual testing
Performed the following manual testing steps on a Linux machine using the canary channel, for which the versioned installer script [gitrinstall-7637176267f01d11dc5725e4b976e4de26d7b9233589438e40f77d18b225d573.sh](https://github.com/cashapp/hermit/releases/download/canary/install-7637176267f01d11dc5725e4b976e4de26d7b9233589438e40f77d18b225d573.sh) is conveniently available (from [a previous merge](https://github.com/cashapp/hermit/pull/257)).

### Build Hermit
```bash
# Build current version. Under ~/Development/hermit
$ make build CHANNEL=canary VERSION=testversion
$ gunzip build/hermit-linux-amd64.gz
$ build/hermit-linux-amd64 version
testversion (canary)
```

### Test bootstrapping (happy path)

```bash
# Clear cache
$ sudo rm -rf ~/.cache/hermit/
# Create test project directory
$ rm -rf /tmp/test-hermit
$ mkdir -p /tmp/test-hermit
$ cd /tmp/test-hermit
# Init using custom built Hermit
$ ~/Development/hermit/build/hermit-linux-amd64 init .
# Manually activate hermit
$ . bin/activate-hermit
...
Hermit environment /tmp/test-hermit activated
# Check hermit version in environment
$ hermit version
7bbf039 (canary) # expected
```

### Test environment validation

Use previous result, under `/tmp/test-hermit` in an activated environment

```bash
# Expect error, for Hermit in canary is not aware of the updated script checksums
$ hermit version
7bbf039 (canary)
$ hermit validate env .
fatal:hermit: /tmp/test-hermit/bin/hermit has an unknown SHA256 signature (49f331b75e8886b5f55d331ad36c0b8304e4402b2ffe7b5e2aa711463babb299); verify that you trust this environment and run 'hermit init /tmp/test-hermit'
# Expect success for custom built hermit
$ ~/Development/hermit/build/hermit-linux-amd64 version
testversion (canary)
$ ~/Development/hermit/build/hermit-linux-amd64 validate env .
$ echo $?
0
$ deactivate-hermit
```

### Test bootstrapping (unhappy path)

Tamper with the expected install script checksum in `bin/hermit` and try bootstrapping

```bash
# Clear cache
$ sudo rm -rf ~/.cache/hermit/
# Create test project directory
$ rm -rf /tmp/test-hermit
$ mkdir -p /tmp/test-hermit
$ cd /tmp/test-hermit
# Init using custom built Hermit
$ ~/Development/hermit/build/hermit-linux-amd64 init .
# In bin/hermit change `awk -v EXPECTED="$INSTALL_SCRIPT_SHA256"` 
# to `awk -v EXPECTED="BAD$INSTALL_SCRIPT_SHA256"`
# Expect checksum failure
$ bin/hermit 
...
Install script sha256 7637176267f01d11dc5725e4b976e4de26d7b9233589438e40f77d18b225d573 does not match BAD7637176267f01d11dc5725e4b976e4de26d7b9233589438e40f77d18b225d573
$ echo $?
1
# Because bin/hermit has been tampered with, environment validation should fail. Just an extra check
$ ~/Development/hermit/build/hermit-linux-amd64 validate env .
fatal:hermit: /tmp/test-hermit/bin/hermit has an unknown SHA256 signature (77fbc28b00979090219e199dcb1a16c9ef5fefa0d4be4498a964ec572de5ab6d); verify that you trust this environment and run 'hermit init /tmp/test-hermit'
```

**Comment by syncom** [comment]
@alecthomas , @jvmakine I was wondering if you folks have any feedback on the manual testing procedures described above, and if you feel comfortable merging it so we can test further using the `canary` build.

**Comment by alecthomas** [comment]
I think it would also be good to test with a cache populated with the previous version, as that is reflects what many users will be using. This should be possible by first installing the previous canary version, then `hermit update` once merged, do an init, etc.

**Comment by syncom** [comment]
Good idea. I created a `Docker` + `mitmproxy`setup to test Hermit update. This setup allows us to test a custom Hermit binary without needing a canary release. 

The steps are described [here](https://github.com/syncom/mitmproxy-hermit/blob/main/README.md). I've tested it using a `hermit-linux-amd64` build created using the current HEAD of this PR branch, with the described steps.

Let me know if it makes sense, @alecthomas  

As a side note, this setup could potentially be useful for testing future Hermit changes.

**Review by alecthomas — APPROVED** [review]

**Pull request merged**
