### PR TITLE
check if deactivate-hermit is defined before calling it

### PR DESCRIPTION
**Pull request by OmarTawfik**
Closes https://github.com/cashapp/hermit/pull/268
Fixes https://github.com/cashapp/hermit/issues/262

### CODE REVIEW

**Comment by quad** [comment]
🆒

**Comment by alecthomas** [comment]
Change itself LGTM but this file is checksummed and Hermit will fail. #273 will offer a clean solution to this, so let's wait until that land before merging.

**Comment by syncom** [comment]
[Looks like](https://github.com/cashapp/hermit/blob/85f382c0a767941f14ac545c734839e6956d652f/shell/posix.go#L16) this template is used to create the `activation` script, which I believe is not checksumed, and does not affect the checksumed files `bin/activate-hermit` and `bin/hermit`. Otherwise, the CI integration test step that checks up-to-date `script.sha256` file should have failed.

**Comment by alecthomas** [comment]
Ah nice.

Though that makes me think we _should_ be checksumming this file.

**Review by alecthomas — APPROVED** [review]

**Comment by alecthomas** [comment]
Thanks @OmarTawfik !

**Pull request merged**
