### PR TITLE
Upgrade to latest Go, golangci-lint

### PR DESCRIPTION
**Pull request by abhinav**
Go 1.19 is not supported anymore.
It won't receive security updates or bugfixes.

Upgrade to the latest release of Go 1.22,
and the latest golangci-lint to actually run with the new Go.

This required a number of linter fixups, or configuration adjustments.
These are detailed in individual commits in the PR.
I tried to make reasonable choices on those issues case-by-case.

I did not bump the 'go' directive in go.mod for now.

### CODE REVIEW

**Comment by abhinav** [comment]
This also requires upgrading golangci-lint. Just a moment.

**Comment by abhinav** [comment]
This is ready for eyes now

**Review by alecthomas — APPROVED** [review]
Apologies for the delay, LGTM!

**Review by alecthomas — APPROVED** [review]

**Comment by abhinav** [comment]
> Apologies for the delay, LGTM!

Not a problem! Thanks for merging.

**Pull request merged**
